services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  cache.pr_googlecse:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['pr_googlecse']

  KronovaNet\PrGooglecse\:
    resource: '../Classes/*'

  KronovaNet\PrGooglecse\SearchPlugin:
    public: true
    arguments:
      $cache: '@cache.pr_googlecse'
